repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: pnpm lint
        language: system
        pass_filenames: false
      - id: typecheck
        name: Type Check
        entry: pnpm type-check
        language: system
        pass_filenames: false
